image: docker:latest

stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.45.1-jammy
  script:
    - npm ci
    - npx playwright test --project=chromium
    - echo "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/playwright-report/index.html"
  allow_failure: true
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 2 days