services:
  regression:
    image: mcr.microsoft.com/playwright:focal
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PATH=/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH
    command: /bin/sh -c "ls -la && npm install && npx playwright test"
    working_dir: /app
    
