services:
  regression:
    image: mcr.microsoft.com/playwright:focal
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: /bin/sh -c "ls -la && apt-get update && apt-get install -y openjdk-11-jdk && npm install && npx playwright test"
    working_dir: /app
    
