name: UI tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run UI-tests via docker-compose
        run: |
          docker compose up

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set JAVA_HOME environment variable
        run: "JAVA_HOME=/opt/hostedtoolcache/Java_Adopt_jdk/11.0.24-8/x64"
      
      - name: Generate Allure report
        run: |
          sudo docker compose run regression /bin/sh -c "npx allure generate allure-results"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true