name: UI tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        run: |
          docker compose up

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          PATH: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: app
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 8

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: $ {{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report