name: UI tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        run: |
          docker compose up

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true

      - name: Set JAVA_HOME environment variable
        run: JAVA_HOME_21_X64=/opt/hostedtoolcache/Java_Zulu_jdk/21.0.4-7/x64
      
      - name: Generate Allure report
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          PATH: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}
        run: |
          sudo docker compose run regression /bin/sh -c "npx allure generate allure-results"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true