name: UI tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run UI-tests via docker-compose
        run: |
          docker compose up

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-report
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 8

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
          destination_dir: app/${{ matrix.test }}